### ISSUE TITLE
新建任务时，团队信息没保存

### ISSUE THREAD

**Issue by douya43** [SeldomQA/seldom-platform#10]

**Comment by defnngj** [comment]
经过我的测试，有保存的！

请使用 `frontend` 前端。

如果确认没有保存，检查前端接口是否有传 `team_id` 参数

![image](https://user-images.githubusercontent.com/1000588/202857475-28062de2-ce06-43d7-80d2-de40e6aad99b.png)

**Comment by defnngj** [comment]
问题已解决
