### ISSUE TITLE
打算接入这个平台，想问下一个git项目中多个测试项目（类似seldom-api-testing），支持这种项目导入吗？

### ISSUE THREAD

**Issue by Gary-CHAO1** [SeldomQA/seldom-platform#17]

**Comment by yongchin0821** [comment]
在新建项目的时候，输入git地址，平台就可以把项目拉到本地进行管理

**Comment by Gary-CHAO1** [comment]
> 在新建项目的时候，输入git地址，平台就可以把项目拉到本地进行管理

谢谢，已经解决。再请问下，项目在本地运行调试要做哪些配置？项目运行起来报404
Using the URLconf defined in backend.urls, Django tried these URL patterns, in this order:

admin/
api/
The empty path didn’t match any of these.

**Comment by yongchin0821** [comment]
> > 在新建项目的时候，输入git地址，平台就可以把项目拉到本地进行管理
> 
> 谢谢，已经解决。再请问下，项目在本地运行调试要做哪些配置？项目运行起来报404 Using the URLconf defined in backend.urls, Django tried these URL patterns, in this order:
> 
> admin/ api/ The empty path didn’t match any of these.

如果还有问题，再另开一个issue吧
