### ISSUE TITLE
团队管理前端报错

### ISSUE THREAD

**Issue by Gary-CHAO1** [SeldomQA/seldom-platform#18]
![image](https://github.com/SeldomQA/seldom-platform/assets/101296901/c49c6736-e245-46ba-b499-3d9ab7d32ad2)

**Comment by yongchin0821** [comment]
前端用的v2还是v3版本？

**Comment by Gary-CHAO1** [comment]
v3版本，使用yarn run dev启动

**Comment by Gary-CHAO1** [comment]
> 前端用的v2还是v3版本？

v3版本，使用yarn run dev启动

**Comment by yongchin0821** [comment]
> 
先yarn install
再yarn dev试试

**Comment by defnngj** [comment]
问题已经解决
