### ISSUE TITLE
点击测试报告后端报错

### ISSUE THREAD

**Issue by 2504973175** [SeldomQA/seldom-platform#27]
get_queryset() got an unexpected keyword argument 'task_id'
Traceback (most recent call last):
  File "E:\Software\Python37\lib\site-packages\ninja\operation.py", line 104, in run
    result = self.view_func(request, **values)
  File "E:\Software\Python37\lib\site-packages\ninja\pagination.py", line 140, in view_with_pagination
    items = func(*args, **kwargs)
  File "F:\seldom-platform\backend\app_task\api.py", line 188, in get_report_list
    return TaskReport.objects.get_queryset(task_id=task_id).order_by("-create_time")[:1000]
TypeError: get_queryset() got an unexpected keyword argument 'task_id'

需要修改get_report_list 方法对应return中调用的方法
![image](https://github.com/SeldomQA/seldom-platform/assets/62871658/42ff1cd0-6805-414a-8197-b0acf6dfd5cf)

**Comment by defnngj** [comment]
![image](https://github.com/SeldomQA/seldom-platform/assets/1000588/61a6be8c-c81b-44eb-a2ad-29d1138b880d)
这个接口是获取报告列表的，ORM查询语句没有错误。

可能出现问题的原因：
1. 你安装的 django/ django-ninjia 版本与我不一致。
2.  你的数据库有 错误的数据导致。

**Comment by defnngj** [comment]
在一次实现分页中，我将  `filter()` 改成了 `get_queryset` ， 不过，已经记不得为什么了。查了 `get_queryset` 貌似和分页没有必然联系。不过，你已经改回来了，非常感谢。

![image](https://github.com/SeldomQA/seldom-platform/assets/1000588/c467298c-59dc-4a95-8c77-9763ed63e61c)
