### ISSUE TITLE
关于类注解的疑问

### ISSUE THREAD

**Issue by lihuacai168** [SeldomQA/seldom-platform#39]
类注解和方法注解这个名字有点奇怪，问了一下gpt，应该是：文档字符串（docstrings）
可以修正一下吗
<img width="588" alt="image" src="https://github.com/user-attachments/assets/0ea5a7fc-e6d2-42b4-9c14-54a5d1501248">

**Comment by defnngj** [comment]
@lihuacai168  感谢，你的说法更准确，我修正一下。
![image](https://github.com/user-attachments/assets/d0c721e2-8bfe-44a5-b4f9-2adb80308be1)
